version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
          override-ci-command:  yarn
      - run:
          command: yarn run test
          name: Run YARN tests
  release:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run semantic-release
          name: Run Semantic Release
workflows:
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - release:
          requires:
            - test
