type File {
  filename: String!
  mimetype: String!
  encoding: String!
}

type Message {
  image: File!
  message: String!
  created_at: Date!
}

extend type Query {
  messages: [Message]
  message(email: EmailAddress!): User
}

extend type Mutation {
  post(image: Upload!, message: String!): Message
}
